all:
  children:
    k8s_master:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          storage_class: local-path
  vars:
    kubeconfig_path: ./tmp/kubeconfig
    namespace: trino-benchmark
    storage_class: local-path
