all:
  children:
    k8s_master:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          storage_class: local-path
  vars:
    # Kubeconfig path - override with -e "kubeconfig_path=/your/path"
    # This gets used by kubernetes.core modules via K8S_AUTH_KUBECONFIG env var
    #kubeconfig_path: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') | default('~/.kube/config', true) }}"
    kubeconfig_path: ./tmp/kubeconfig
    namespace: trino-benchmark
    storage_class: local-path
